.TH KIWIX 1 "21 May 2012"
.SH NAME
Kiwix \- Lecteur hors-ligne de fichiers ZIM
.SH SYNOPSIS
.B kiwix [-jsconsole]
.SH DESCRIPTION
.PP
Kiwix est un lecteur de content au format ZIM.
.br
Les fichiers ZIM sont des archives de contenus compressés (généralement HTML)
.br
Les fichiers ZIM les plus populaires sont ceux de Wikipédia et Wikileaks.

.TP
\fB\-jsconsole\fR
Active la console de debogage JavaScript de Xulrunner.

.PP
Fonctionnalités:
 * Lecteur de ZIM natif
 * Moteur de recherche plein texte.
 * Signets et Notes
 * Serveur Web pour diffuser les fichiers ZIM sur le réseau.
 * Export HTML et PDF.
 * Traduits dans de nombreuses langues.
 * Suggestions de recherche.
 * Indexation des fichiers ZIM.
 * Onglets de navigation.
 * Bibliothèque de contenus intégrée.

.SH SEE ALSO
kiwix-index(1) kiwix-install(1) kiwix-serve(1)
.br
kiwix-compact(1) kiwix-manage(1)

.SH AUTHORS
 Emmanuel Engelhart <kelson@kiwix.org>
 Guillaume Duhamel <gduhamel@linterweb.com>
 Fabien Coullon <fcoulon@linterweb.com>
 Renaud Gaudin <rgaudin@gmail.com>
 Wilfredo Rodriguez <wilfredor@kiwix.org>
.br
Vasudev Kamath <kamathvasudev@gmail.com> (Manual)