.TH kiwix-serve 1 "21 May 2012" "0.1" "Kiwix HTTP Server"
.SH NAME
kiwix-serve \- Kiwix HTTP Server
.SH SYNOPSIS
.B kiwix-serve
.SH DESCRIPTION
Serves a ZIM file or a Kiwix library over HTTP for in-browser access.
.SH SEE ALSO
kiwix(1) kiwix-index(1) kiwix-install(1) kiwix-compact(1) kiwix-manage(1)
.SH AUTHOR
Emmanuel Engelhart <kelson@kiwix.org>