.TH kiwix-compact 1 "21 May 2012" "0.1" "ZIM index compacter"
.SH NAME
kiwix-compact \- ZIM index compacter
.SH SYNOPSIS
.B kiwix-compact
.SH DESCRIPTION
Compacts ZIM files used by Kiwix using xapian-compact
.SH SEE ALSO
kiwix(1) kiwix-index(1) kiwix-install(1) kiwix-serve(1) kiwix-manage(1) xapian-compact(1)
.SH AUTHOR
Emmanuel Engelhart <kelson@kiwix.org>