.TH KIWIX-READ "1" "July 2020" "kiwix-tools" "User Commands"
.SH NAME
kiwix-read \- Read ZIM file content
.SH SYNOPSIS
\fBkiwix-read\fR [\-\-verbose] [\-\-version] \-\-suggest=PATTERN ZIM\fR
.SH DESCRIPTION
.TP
ZIM
ZIM file to search
.TP
\fB\-\-verbose\fR
Enable extra output
.TP
\fB\-\-version\fR
print software version
.TP
\fB\-\-suggest=PATTERN\fR
Get search suggestions for the provided pattern
