.TH KIWIX-MANAGE 1 "21 May 2012"

.SH NAME
kiwix\-manage \- Kiwix Library Manager

.SH SYNOPSIS
.IX Header SYNOPSIS
.TP
\fBkiwix\-manage\fR LIBRARY_PATH \fBadd\fR ZIM_PATH ...
.TP
\fBkiwix\-manage\fR LIBRARY_PATH \fBshow\fR [ZIM_ID_1] [ZIM_ID_2] ...
.TP
\fBkiwix\-manage\fR LIBRARY_PATH \fBremove\fR ZIM_ID_1 [ZIM_ID_2] ...
.TP
\fBkiwix\-manage\fR --version
.TP
\fBkiwix\-manage\fR --help

.SH DESCRIPTION
.PP
\fBkiwix\-manage\fP is a command line tool for manipulating a Kiwix XML library.
.PP
\fBkiwix\-manage\fP allows to manage the entries of the Kiwix
library. The library file is a flat XML file listing ZIM files with
all necessary information like id, favicon, date, creator,
description, filepath, title, url, etc.

.SH ACTIONS

.TP
\fBadd\fR
Add \fBZIM_FILE\fP to \fBLIBRARY_FILE\fP. Create the library file if necessary.

.TP
\fBremove\fR
Remove the given \fBZIM_ID\fR from \fBLIBRARY_FILE\fR. At least one \fBZIM_ID\fR should be specified.

.TP
\fBshow\fR
Show given \fBZIM_ID\fP from \fBLIBRARY_FILE\fR. If no \fBZIM_ID\fP is given then all contents from \fBLIBRARY_FILE\fR are shown.

.SH OPTIONS
.TP
Options to be used with the action \fBadd\fR:

.TP
\fB\-\-url=HTTP_URL\fR
Set the ZIM online HTTP(S) URL

.TP
\fB\-\-zimPathToSave=OTHER_FS_PATH\fR
Set an arbitrary ZIM filesystem path (instead of the ZIM_PATH)

.TP
Other options (to be used alone):

.TP
\fB\-\-help | \-h\fR
Display the kiwix-manage help

.TP
\fB\-\-version | \-v\fR
Display the version of kiwix-manage and all dependences

.SH SEE ALSO
kiwix\-serve(1)

.SH AUTHORS
Kiwix team <contact@kiwix.org>
