.TH KIWIX 1 "21 May 2012"
.SH NAME
kiwix\-serve \- Kiwix HTTP Server
.SH SYNOPSIS
.IX Header "SYNOPSIS"
.br
kiwix\-serve [\-\-index=INDEX_PATH] [\-\-port=PORT] [\-\-verbose] [\-\-daemon] [\-\-attachToProcess=PID] ZIM_PATH
.br
kiwix\-serve \-\-library [\-\-port=PORT] [\-\-verbose] [\-\-daemon] [\-\-attachToProcess=PID] LIBRARY_PATH
.SH DESCRIPTION
.PP
Stand\-alone HTTP server for serving ZIM content over the network.

.TP
\fB\-\-index=INDEX_PATH\fR
Path to index folder created using \fBkiwix-install\fB.

.TP
\fB\-\-port=PORT\fR
Port number on which the server should listen.
.br
By default, server listens on port 80.

.TP
\fB\-\-verbose\fR
Enable verbose output.

.TP
\fB\-\-daemon\fR
Run the server as a daemon

.TP
\fB\-\-attachToProcess=PID\fR
Shutdown the server when process numbered PID dies.

.TP
\fBZIM_PATH\fR
ZIM file of the content to serve.
.br
Mandatory if not in library mode.

.TP
\fB\-\-library\fR
Enable library mode.
.br
Serves the contents of a library file instead of a single ZIM file.

.TP
\fBLIBRARY_PATH\fR
Kiwix library file path.
.br
Library is XML file created using \fBkiwix-manage\fB.

.SH SEE ALSO
kiwix(1) kiwix\-manage(1)
.br
kiwix\-install(1)
.SH AUTHOR
Emmanuel Engelhart <kelson@kiwix.org>
.br
Vasudev Kamath <kamathvasudev@gmail.com> (Manual)
