.TH KIWIX 1 "21 May 2012"
.SH NAME
Kiwix \- Offline ZIM file reader
.SH SYNOPSIS
.B kiwix [-jsconsole]
.SH DESCRIPTION
.PP
Kiwix allows you to read and search through offline content
.br
as they were online on the Web. Similar to a browser, Kiwix works with
.br
the highly compressed ZIM file format.

.TP
\fB\-jsconsole\fR
Enables the Javascript Debug console (Xulrunner)

.PP
Features:
 * Pure ZIM file reader
 * Case and diacritics insensitve full text search engine
 * Bookmarks & Notes
 * ZIM base HTTP server
 * PDF/HTML export
 * Localized
 * Search suggestions
 * ZIM file Index capacity
 * Tabs navigation
 * Content manager

.SH SEE ALSO
kiwix-index(1) kiwix-install(1) kiwix-serve(1)
.br
kiwix-compact(1) kiwix-manage(1)

.SH AUTHORS
 Emmanuel Engelhart <kelson@kiwix.org>
 Guillaume Duhamel <gduhamel@linterweb.com>
 Fabien Coullon <fcoulon@linterweb.com>
 Renaud Gaudin <rgaudin@gmail.com>
 Wilfredo Rodriguez <wilfredor@kiwix.org>
 .br
Vasudev Kamath <kamathvasudev@gmail.com> (Manual)