.TH KIWIX 1 "21 May 2012"
.SH NAME
kiwix\-serve \- Serveur Web Kiwix
.SH SYNOPSIS
.IX Header "SYNOPSIS"
.br
kiwix\-serve [\-\-index=INDEX_PATH] [\-\-port=PORT] [\-\-verbose] [\-\-daemon] [\-\-attachToProcess=PID] ZIM_PATH
.br
kiwix\-serve \-\-library [\-\-port=PORT] [\-\-verbose] [\-\-daemon] [\-\-attachToProcess=PID] LIBRARY_PATH
.SH DESCRIPTION
.PP
Serveur Web (HTTP) autonome pour diffuser des contenus ZIM sur le réseau.

.TP
\fB\-\-index=INDEX_PATH\fR
Chemin vers l'index plein text du fichier ZIM.

.TP
\fB\-\-port=PORT\fR
Port sur lequel le serveur doit écouter.
.br
Par défaut, le serveur écoute sur le port 80.

.TP
\fB\-\-verbose\fR
Active le mode verbeux de la sortie.

.TP
\fB\-\-daemon\fR
Execute le serveur en mode démon.

.TP
\fB\-\-attachToProcess=PID\fR
Arrêter le serveur lorsque que le processus PID meurt.

.TP
\fBZIM_PATH\fR
Chemin vers le fichier ZIM à diffuser.
.br
Obligatoire en dehors du mode bibliothèque.

.TP
\fB\-\-library\fR
Active le mode bibliothèque.
.br
Sert les contenus d'une bibliothèque Kiwix au lieu d'un seul fichier ZIM.

.TP
\fBLIBRARY_PATH\fR
Chemin vers le fichier bibliothèque de Kiwix.
.br
Le fichier bibliothèque est un fichier XML créé avec \fBkiwix-manage\fB.

.SH SEE ALSO
kiwix(1) kiwix\-manage(1)
.br
kiwix\-install(1)
.SH AUTHOR
Emmanuel Engelhart <kelson@kiwix.org>
.br
Vasudev Kamath <kamathvasudev@gmail.com> (Manual)
